/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_rbehjati_genie_Jenny */

#ifndef _Included_io_rbehjati_genie_Jenny
#define _Included_io_rbehjati_genie_Jenny
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_rbehjati_jenny_Jenny
 * Method:    generator
 * Signature: (I[Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_rbehjati_genie_Jenny_generator
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
